stages:
  - lint
  - build
  - publish
  - release
  - deploy

variables:
  CONTAINER_IMAGE_NAME: $DOCKER_HUB_USER/cchgeu-frontend

default:
  image: node:20
  before_script:
    - corepack enable pnpm

cache:
  paths:
    - node_modules/
    - dist
    - deploy

include:
  - local: .gitlab/ci/*.gitlab-ci.yml
