stages:
  - lint
  - build
  - release
  # - deploy

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  DEV_USER: slincnik
  DEV_HOME: /home/${DEV_USER}
  DEV_HOST: 185.175.45.94
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

default:
  image: node:20
  before_script:
    - corepack enable pnpm

cache:
  paths:
    - node_modules/
    - dist
    - deploy

include:
  - local: .gitlab/ci/*.gitlab-ci.yml
