version: '3.8'

services:
  ui:
    container_name: cchgeu-ui-v2
    image: ${CONTAINER_IMAGE_NAME}:latest
    env_file: deploy.env
    ports:
      - "4200:80"
    networks:
      - assistant

networks:
  assistant:
    name: assistant
    driver: bridge
    external: true
