lint-job:
  stage: lint
  cache:
    key: "node-modules-cache-${CI_COMMIT_REF_SLUG}-$(sha256sum pnpm-lock.yaml | cut -d' ' -f1)"
    paths:
      - node_modules/
    policy: push
    expire_in: "2 weeks"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: '$CI_MERGE_REQUEST_IID'
  before_script:
    - corepack enable pnpm
    - pnpm install --frozen-lockfile --ignore-scripts
  script:
    - pnpm lint'

build-job:
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  needs:
    - lint-job
  script:
    - pnpm run build
