lint-job:
  stage: lint
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME == "dev"
    - if: '$CI_MERGE_REQUEST_IID'
  before_script:
    - corepack enable pnpm
    - pnpm install --frozen-lockfile --ignore-scripts
  script:
    - pnpm lint
  artifacts:
    paths:
      - node_modules/

build-job:
  stage: build
  before_script:
    - corepack enable pnpm
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME == "dev"
  needs:
    - job: lint-job
      artifacts: true
  script:
    - pnpm run build
