release-job:
  stage: release
  needs:
    - build-job
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD docker.io
  script:
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Release $CI_COMMIT_TAG'
    description: 'Release created'


deploy-job:
  stage: deploy
  image: alpine:3.18
  needs:
    - release-job
  before_script:
    - apk update && apk add bash
    - apk update && apk add gettext
    - apk add openssh-client bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
  script:
    - ssh ${DEV_USER}@${DEV_HOST} "mkdir -p /tmp/${CI_PROJECT_DIR}/frontend/"
    - scp ./deploy/front.conf ${DEV_USER}@${DEV_HOST}:/tmp/${CI_PROJECT_DIR}/frontend/default.conf
    - envsubst < ./deploy/deploy.sh| ssh ${DEV_USER}@${DEV_HOST}

workflow:
  rules:
    - if: '$CI_COMMIT_TAG'